{% set name = "qt-dev-helper" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qt_dev_helper-{{ version }}.tar.gz
  sha256: 789b85a6e64d1601cc42a000599b2bfb7481cebb501d759b97a8dfcaa981ac88

build:
  entry_points:
    - qt-dev-helper=qt_dev_helper.cli.main_app:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - pydantic >=1.9.0
    - rich >=12.0.0
    - tomli >=2.0.1
    - typer >=0.4.0
    - qtsass >=0.3.1

test:
  imports:
    - qt_dev_helper
  commands:
    - pip check
    - qt-dev-helper --help
  requires:
    - pip

about:
  home: https://github.com/s-weigand/qt-dev-helper
  summary: Tool to help developing Qt applications
  dev_url: https://github.com/s-weigand/qt-dev-helper
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - s-weigand
    - jsnel
